spring.application.name=portfolio

spring.datasource.url= jdbc:postgresql://localhost:5432/Portfolio
spring.datasource.username=postgres
spring.datasource.password=12345678909

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

server.port=8081

cloudinary.cloud-name=dl5e6thva
cloudinary.api-key=557538721261468
cloudinary.api-secret=yRoCZAAOcVMyuCsd85fx7nM6Z90

# Overriding Spring's default 1MB restriction to accommodate rich images
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB