spring.application.name=portfolio

# \uD83C\uDF1F EXPLICIT DESKTOP DIRECT BINDING
spring.datasource.url= jdbc:postgresql://ep-divine-credit-ao71kq6p.c-2.ap-southeast-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_AQVJocpYm6D2&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_AQVJocpYm6D2

#spring.datasource.url= jdbc:postgresql://localhost:5432/Portfolio
#spring.datasource.username=postgres
#spring.datasource.password=12345678909



#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#server.port=8081

portfolio.app.admin.password=6267494475
portfolio.app.guest.password=guest123
cloudinary.cloud-name=dl5e6thva
cloudinary.api-key=557538721261468
cloudinary.api-secret=yRoCZAAOcVMyuCsd85fx7nM6Z90

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

portfolio.frontend.url=https://shubham-portfolio-aoal8lbyy-shubham-makode-s-projects.vercel.app